const medicalOptions = [
    { value: "abortions", label: "abortions" },
    { value: "ACIDITY", label: "ACIDITY" },
    { value: "ADV BSL", label: "ADV BSL" },
    { value: "ALCOHOL DEP", label: "ALCOHOL DEP" },
    { value: "alopecia", label: "alopecia" },
    { value: "AMI", label: "AMI" },
    { value: "ANEMIA", label: "ANEMIA" },
    { value: "ANGIOPLASTY", label: "ANGIOPLASTY" },
    { value: "appendicectomy", label: "appendicectomy" },
    { value: "appendicitis", label: "appendicitis" },
    { value: "ARTHRITIS", label: "ARTHRITIS" },
    { value: "asthama", label: "asthama" },
    { value: "astrocytoma", label: "astrocytoma" },
    { value: "ATTEMPTING SUICIDE", label: "ATTEMPTING SUICIDE" },
    { value: "B E PROSTATE", label: "B E PROSTATE" },
    { value: "B12 def", label: "B12 def" },
    { value: "basal  ganglia", label: "basal  ganglia" },
    { value: "BASILAR ARTERY", label: "BASILAR ARTERY" },
    { value: "BELLS PALSY", label: "BELLS PALSY" },
    { value: "BEP", label: "BEP" },
    { value: "BILATERAL HOLE IN EARDRUM", label: "BILATERAL HOLE IN EARDRUM" },
    { value: "bladder neck obstruction", label: "bladder neck obstruction" },
    { value: "Blood clots", label: "Blood clots" },
    { value: "BYPASS", label: "BYPASS" },
    { value: "CA BREAST", label: "CA BREAST" },
    { value: "CA OESO", label: "CA OESO" },
    { value: "CA PAROTID", label: "CA PAROTID" },
    { value: "cardiac bypass", label: "cardiac bypass" },
    { value: "Cardiac Disease", label: "Cardiac Disease" },
    { value: "CATARACT SURGERY", label: "CATARACT SURGERY" },
    { value: "cerebral white matter", label: "cerebral white matter" },
    { value: "CHICKEN GUNIA", label: "CHICKEN GUNIA" },
    { value: "CHOLECYSTECTOMY", label: "CHOLECYSTECTOMY" },
    { value: "CHOREA", label: "CHOREA" },
    { value: "colitis", label: "colitis" },
    { value: "COMA", label: "COMA" },
    { value: "convulsions", label: "convulsions" },
    { value: "CORONARY BLOCK", label: "CORONARY BLOCK" },
    { value: "COVID +", label: "COVID +" },
    { value: "CREBRAL ATROPHY", label: "CREBRAL ATROPHY" },
    { value: "CVA", label: "CVA" },
    { value: "CX SPONDI", label: "CX SPONDI" },
    { value: "DELAYED MILESTONES", label: "DELAYED MILESTONES" },
    { value: "DEMENTIA", label: "DEMENTIA" },
    { value: "DENGUE", label: "DENGUE" },
    { value: "diabetic neuro", label: "diabetic neuro" },
    { value: "difficulty in urine", label: "difficulty in urine" },
    { value: "disability", label: "disability" },
    { value: "DM", label: "DM" },
    { value: "ear lesion", label: "ear lesion" },
    { value: "EAR PAIN WAX", label: "EAR PAIN WAX" },
    { value: "ENCEPHELITIS", label: "ENCEPHELITIS" },
    { value: "ENDOMETRIOSIS", label: "ENDOMETRIOSIS" },
    { value: "epilepsy", label: "epilepsy" },
    { value: "EPR", label: "EPR" },
    { value: "FACIAL PALSY", label: "FACIAL PALSY" },
    { value: "fainting attack", label: "fainting attack" },
    { value: "FATTY LIVER", label: "FATTY LIVER" },
    { value: "FEAR OF HEMIPLEGIA", label: "FEAR OF HEMIPLEGIA" },
    { value: "fear of hiv", label: "fear of hiv" },
    { value: "febrile convulsion", label: "febrile convulsion" },
    { value: "febrile illness", label: "febrile illness" },
    { value: "fever", label: "fever" },
    { value: "fibroid", label: "fibroid" },
    { value: "fissure", label: "fissure" },
    { value: "fistula", label: "fistula" },
    { value: "FOCAL SEIZURE", label: "FOCAL SEIZURE" },
    { value: "GALL STONES", label: "GALL STONES" },
    { value: "GANJA  DEP", label: "GANJA  DEP" },
    { value: "GASTRITIS", label: "GASTRITIS" },
    { value: "GEREBRAL ATROPHY", label: "GEREBRAL ATROPHY" },
    { value: "GIDDINESS", label: "GIDDINESS" },
    { value: "glaucoma", label: "glaucoma" },
    { value: "GOITRE", label: "GOITRE" },
    { value: "H/O  EPI", label: "H/O  EPI" },
    { value: "H/O  P V BLEEDING", label: "H/O  P V BLEEDING" },
    { value: "h/o incontinance", label: "h/o incontinance" },
    { value: "head inj", label: "head inj" },
    { value: "HEADACHE", label: "HEADACHE" },
    { value: "HEARING LOSS", label: "HEARING LOSS" },
    { value: "hematemesis", label: "hematemesis" },
    { value: "HEMICOLONECTOMY", label: "HEMICOLONECTOMY" },
    { value: "Hemiplegia", label: "Hemiplegia" },
    { value: "HEPATITIS B'", label: "HEPATITIS B'" },
    { value: "HERNIA", label: "HERNIA" },
    { value: "HERPES", label: "HERPES" },
    { value: "HIV +VE", label: "HIV +VE" },
    { value: "HT", label: "HT" },
    { value: "HT ON AMLOVAS", label: "HT ON AMLOVAS" },
    { value: "HYDROCOELE", label: "HYDROCOELE" },
    { value: "HYPERACTIVE BLADDER", label: "HYPERACTIVE BLADDER" },
    { value: "hypodensity in lt paritalcortex", label: "hypodensity in lt paritalcortex" },
    { value: "HYPONATREMIA", label: "HYPONATREMIA" },
    { value: "HYPOTHALAMIC HAMARTOMA", label: "HYPOTHALAMIC HAMARTOMA" },
    { value: "hypothyroidism", label: "hypothyroidism" },
    { value: "HYSTERECTOMY", label: "HYSTERECTOMY" },
    { value: "incontinence urine", label: "incontinence urine" },
    { value: "INFARCT", label: "INFARCT" },
    { value: "INTESTINAL OBSTRUCTION", label: "INTESTINAL OBSTRUCTION" },
    { value: "INTRACEREBRAL BLEED", label: "INTRACEREBRAL BLEED" },
    { value: "involuntary movements", label: "involuntary movements" },
    { value: "JAUNDICE", label: "JAUNDICE" },
    { value: "KETO ACIDOSIS", label: "KETO ACIDOSIS" },
    { value: "KIDNEY NONFUNCTIONIN", label: "KIDNEY NONFUNCTIONIN" },
    { value: "KIDNEY REMOVED", label: "KIDNEY REMOVED" },
    { value: "LBBB LT STRAIN", label: "LBBB LT STRAIN" },
    { value: "leprosy", label: "leprosy" },
    { value: "LEUKOCYTOSIS", label: "LEUKOCYTOSIS" },
    { value: "LEUKODERMA", label: "LEUKODERMA" },
    { value: "LITHIUM INDUCED NEPHROTOXICITY", label: "LITHIUM INDUCED NEPHROTOXICITY" },
    { value: "LIVER CIRRHOSIS", label: "LIVER CIRRHOSIS" },
    { value: "LONG STANDING DEGENERATIVE BRAIN DIS", label: "LONG STANDING DEGENERATIVE BRAIN DIS" },
    { value: "long term abdo discmfort", label: "long term abdo discmfort" },
    { value: "low grade glema", label: "low grade glema" },
    { value: "LT ARTERY DIS", label: "LT ARTERY DIS" },
    { value: "LT POST PARITAL LOBE BLEED", label: "LT POST PARITAL LOBE BLEED" },
    { value: "LT renal calculus", label: "LT renal calculus" },
    { value: "LT THALAMUS HEMORRHAGE", label: "LT THALAMUS HEMORRHAGE" },
    { value: "MALIGNANCY", label: "MALIGNANCY" },
    { value: "MENINGITIS", label: "MENINGITIS" },
    { value: "MEPHENTERINE ADDICTION", label: "MEPHENTERINE ADDICTION" },
    { value: "migraine", label: "migraine" },
    { value: "MILD CEREBRAL", label: "MILD CEREBRAL" },
    { value: "mitral valve surgery", label: "mitral valve surgery" },
    { value: "myasthenia", label: "myasthenia" },
    { value: "MYOCLONUS", label: "MYOCLONUS" },
    { value: "nantral GASTRITIS WITH ULCER", label: "nantral GASTRITIS WITH ULCER" },
    { value: "NEUROLOGICAL PROBLEM", label: "NEUROLOGICAL PROBLEM" },
    { value: "ORAL SURGERY", label: "ORAL SURGERY" },
    { value: "osteoporosis", label: "osteoporosis" },
    { value: "OVARIAN CYST", label: "OVARIAN CYST" },
    { value: "PARKINSON", label: "PARKINSON" },
    { value: "PARTIAL SEIZURE", label: "PARTIAL SEIZURE" },
    { value: "PCOD", label: "PCOD" },
    { value: "PEPTIC ULCER", label: "PEPTIC ULCER" },
    { value: "PILES", label: "PILES" },
    { value: "PLAQUE", label: "PLAQUE" },
    { value: "poliomyelitis", label: "poliomyelitis" },
    { value: "portal vein thrombosis", label: "portal vein thrombosis" },
    { value: "ppperiod daughter", label: "ppperiod daughter" },
    { value: "PROCTITIS", label: "PROCTITIS" },
    { value: "PROSTATE REMOVED", label: "PROSTATE REMOVED" },
    { value: "PSEUDOBULBAR PALSY", label: "PSEUDOBULBAR PALSY" },
    { value: "PSORIASIS", label: "PSORIASIS" },
    { value: "PULMONARY HT", label: "PULMONARY HT" },
    { value: "RECTAL ULCER", label: "RECTAL ULCER" },
    { value: "renal dis", label: "renal dis" },
    { value: "RENAL STONE", label: "RENAL STONE" },
    { value: "RENAL STONES SURGERY", label: "RENAL STONES SURGERY" },
    { value: "RHEUMATI HEART DISEASE", label: "RHEUMATI HEART DISEASE" },
    { value: "RHEUMATIC AORTIC REGURG", label: "RHEUMATIC AORTIC REGURG" },
    { value: "ROOT CANAL", label: "ROOT CANAL" },
    { value: "RT LT DISORIENTATION", label: "RT LT DISORIENTATION" },
    { value: "RT PLEURAL EFFUSION", label: "RT PLEURAL EFFUSION" },
    { value: "RT TEMPOROPARITAL LOBE GLIOSIS", label: "RT TEMPOROPARITAL LOBE GLIOSIS" },
    { value: "RUM FIT", label: "RUM FIT" },
    { value: "RUM FITS WITHDRAWAL", label: "RUM FITS WITHDRAWAL" },
    { value: "SCLEROSIS", label: "SCLEROSIS" },
    { value: "SEIZURE", label: "SEIZURE" },
    { value: "SGOT", label: "SGOT" },
    { value: "SGPT", label: "SGPT" },
    { value: "SPONDILYSIS", label: "SPONDILYSIS" },
    { value: "STROKE", label: "STROKE" },
    { value: "TADI DEP", label: "TADI DEP" },
    { value: "TEMPORAL MESIAL", label: "TEMPORAL MESIAL" },
    { value: "thyroid", label: "thyroid" },
    { value: "THYROIDECTOMY", label: "THYROIDECTOMY" },
    { value: "TIA", label: "TIA" },
    { value: "TREMOR SYNDROME", label: "TREMOR SYNDROME" },
    { value: "TUBECTOMY SURG", label: "TUBECTOMY SURG" },
    { value: "URINARY RETENTION", label: "URINARY RETENTION" },
    { value: "URTICARIA", label: "URTICARIA" },
    { value: "VALVULAR DIS", label: "VALVULAR DIS" },
    { value: "VERTIGO", label: "VERTIGO" },
    { value: "VIRAL ENCEPHELITIS", label: "VIRAL ENCEPHELITIS" },
    { value: "VISUAL IMPAIREMENT", label: "VISUAL IMPAIREMENT" },
    { value: "VISUAL LOSS", label: "VISUAL LOSS" },
    { value: "WATERING OF EAR RT", label: "WATERING OF EAR RT" },
    { value: "WIDENING OF RT TEMPORAL LOBE", label: "WIDENING OF RT TEMPORAL LOBE" },
    { value: "WITHDRAWAL SEIZURES", label: "WITHDRAWAL SEIZURES" },
    { value: "WORD RECALL IMPAIRED", label: "WORD RECALL IMPAIRED" }
]
export default medicalOptions