const prescriptionOptions = [
    { value: "Arip MT", label: "Arip MT" },
    { value: "Asprito", label: "Asprito" },
    { value: "Bupron XL", label: "Bupron XL" },
    { value: "Depranex", label: "Depranex" },
    {value: "Depravine", label: "Depravine"},
    { value: "Depsonil", label: "Depsonil" },
    { value: "Duvanta", label: "Duvanta" },
    { value: "Duzela", label: "Duzela" },
    { value: "Ecitelo", label: "Ecitelo" },
    { value: "Escident", label: "Escident" },
    { value: "Floatin", label: "Floatin" },
    { value: "Flunil", label: "Flunil" },
    { value: "Flutop LA", label: "Flutop LA" },
    { value: "Galop", label: "Galop" },
    { value: "Mirnite", label: "Mirnite" },
    { value: "Mirsol", label: "Mirsol" },
    { value: "Nexito", label: "Nexito" },
    { value: "Oliza", label: "Oliza" },
    { value: "Prodep", label: "Prodep" },
    { value: "Pari", label: "Pari" },
    { value: "Pari CR", label: "Pari CR" },
    { value: "Paxinta CR", label: "Paxinta CR" },
    { value: "Pexep", label: "Pexep" },
    { value: "Pexep plus", label: "Pexep Plus" },
    { value: "PexepCR", label: "PexepCR" },
    { value: "Relicalm plus", label: "Relicalm Plus" },
    { value: "Restonorm", label: "Restonorm" },
    { value: "Restonorm F", label: "Restonorm F" },
    { value: "Restonorm LS", label: "Restonorm LS" },
    { value: "Restonorm plus", label: "Restonorm Plus" },
    { value: "Rexipra", label: "Rexipra" },
    { value: "Risdone", label: "Risdone" },
    { value: "Risdone fort", label: "Risdone Fort" },
    { value: "Risdone LS", label: "Risdone LS" },
    { value: "Risdone liquid", label: "Risdone Liquid" },
    { value: "Risdone plus", label: "Risdone Plus" },
    { value: "Rospitril", label: "Rospitril" },
    { value: "Rospitril plus", label: "Rospitril Plus" },
    { value: "Serenace", label: "Serenace" },
    { value: "Serlift", label: "Serlift" },
    { value: "Sermind", label: "Sermind" },
    { value: "Serta", label: "Serta" },
    { value: "Sertima", label: "Sertima" },
    { value: "Sizodon", label: "Sizodon" },
    { value: "Sizodon fort", label: "Sizodon fort" },
    { value: "Sizodon LS", label: "Sizodon LS" },
    { value: "Sizodon plus", label: "Sizodon plus" },
    { value: "Szetalo", label: "Szetalo" },
    { value: "Trinicalm fort", label: "Trinicalm fort" },
    { value: "Trinicalm plus", label: "Trinicalm plus" },
    { value: "Trazine H", label: "Trazine H" },
    { value: "Trazine S", label: "Trazine S" },
    { value: "Trazine SC", label: "Trazine SC" },
    { value: "Yemetil", label: "Yemetil" },
    { value: "Zaptra", label: "Zaptra" },
    { value: "Zupion SR", label: "Zupion SR" },
]
export default prescriptionOptions