const symptomsOptions = [
    { value: "ABDOMINAL PAIN", label: "ABDOMINAL PAIN" },
    { value: "ABUSIVE", label: "ABUSIVE" },
    { value: "ACIDITY", label: "ACIDITY" },
    { value: "AGGRESSIVE  BEHAVIOUR", label: "AGGRESSIVE  BEHAVIOUR" },
    { value: "ANGRY OUTBURSTS", label: "ANGRY OUTBURSTS" },
    { value: "BELCHING", label: "BELCHING" },
    { value: "BODY ACHE", label: "BODY ACHE" },
    { value: "BURNING SENSATION-BODY", label: "BURNING SENSATION-BODY" },
    { value: "BURNING SENSATION-HEAD", label: "BURNING SENSATION-HEAD" },
    { value: "CATATONIA-ECHOLALIA", label: "CATATONIA-ECHOLALIA" },
    { value: "CATATONIA-ECHOPRAXIA", label: "CATATONIA-ECHOPRAXIA" },
    { value: "CATATONIA-NEGATIVISM", label: "CATATONIA-NEGATIVISM" },
    { value: "CATATONIA-POSTURING", label: "CATATONIA-POSTURING" },
    { value: "CATATONIA-WAXIFLEXIBILITY", label: "CATATONIA-WAXIFLEXIBILITY" },
    { value: "CHEST PAIN", label: "CHEST PAIN" },
    { value: "CHOKING SENSATION", label: "CHOKING SENSATION" },
    { value: "CIRCUMSTANTIALITY", label: "CIRCUMSTANTIALITY" },
    { value: "CONSTIPATION", label: "CONSTIPATION" },
    { value: "DANCING", label: "DANCING" },
    { value: "ERICTILE DISFUNCTION", label: "ERICTILE DISFUNCTION" },
    { value: "EXCESSIVE SOCIALIZATION", label: "EXCESSIVE SOCIALIZATION" },
    { value: "EXCESSIVE SPENDING", label: "EXCESSIVE SPENDING" },
    { value: "FEAR OF DEATH", label: "FEAR OF DEATH" },
    { value: "FEAR OF DISEASE", label: "FEAR OF DISEASE" },
    { value: "FEAR OF HEARTATTACK", label: "FEAR OF HEARTATTACK" },
    { value: "FEAR OF MALIGNANCY", label: "FEAR OF MALIGNANCY" },
    { value: "FEAR OF MENTAL ILLNESS", label: "FEAR OF MENTAL ILLNESS" },
    { value: "FEAR OF PARALYSIS", label: "FEAR OF PARALYSIS" },
    { value: "FEARFULLNESS", label: "FEARFULLNESS" },
    { value: "FEELING PRESSURE ON CHEST", label: "FEELING PRESSURE ON CHEST" },
    { value: "FLIGHTS OF IDEAS", label: "FLIGHTS OF IDEAS" },
    { value: "FORGETFULNESS", label: "FORGETFULNESS" },
    { value: "FORIGN BODY IN THROAT", label: "FORIGN BODY IN THROAT" },
    { value: "GASEOUS ERUPTION", label: "GASEOUS ERUPTION" },
    { value: "GAZE AVOIDANCE", label: "GAZE AVOIDANCE" },
    { value: "GIDDINESS", label: "GIDDINESS" },
    { value: "GRANDIOSITY", label: "GRANDIOSITY" },
    { value: "GUILT FEELING", label: "GUILT FEELING" },
    { value: "HEADACHE", label: "HEADACHE" },
    { value: "HEAVINESS IN HEAD", label: "HEAVINESS IN HEAD" },
    { value: "HICCUPS", label: "HICCUPS" },
    { value: "IMPAIRED SELF CARE", label: "IMPAIRED SELF CARE" },
    { value: "IMPULSIVE  GAMBLING", label: "IMPULSIVE  GAMBLING" },
    { value: "INCOHERENT TALK", label: "INCOHERENT TALK" },
    { value: "INCREASED ANXIETY SYMPTOMS ON HEARING NEWS OF DEATH", label: "INCREASED ANXIETY SYMPTOMS ON HEARING NEWS OF DEATH" },
    { value: "INCREASED IRRITABLITY", label: "INCREASED IRRITABLITY" },
    { value: "INCREASED RELIGIOUSITY", label: "INCREASED RELIGIOUSITY" },
    { value: "INCREASED SOCIALIZATION", label: "INCREASED SOCIALIZATION" },
    { value: "IRRELEVANT TALK", label: "IRRELEVANT TALK" },
    { value: "KLEPTOMANIA", label: "KLEPTOMANIA" },
    { value: "LACK OF CONFIDENCE", label: "LACK OF CONFIDENCE" },
    { value: "LACK OF INITIATIVE", label: "LACK OF INITIATIVE" },
    { value: "LAUGHING TO  SELF", label: "LAUGHING TO  SELF" },
    { value: "LOSS OF CONCENTRATION", label: "LOSS OF CONCENTRATION" },
    { value: "LOSS OF ENTHUSIASM", label: "LOSS OF ENTHUSIASM" },
    { value: "LOSS OF LIBIDO", label: "LOSS OF LIBIDO" },
    { value: "MUTTERING TO SELF", label: "MUTTERING TO SELF" },
    { value: "NECK PAIN", label: "NECK PAIN" },
    { value: "NERVOUSNESS", label: "NERVOUSNESS" },
    { value: "NOT WORKING", label: "NOT WORKING" },
    { value: "NOT TAKING CARE OF CHILDREN", label: "NOT TAKING CARE OF CHILDREN" },
    { value: "OBSESSIVE SEXUAL THOUGHTS", label: "OBSESSIVE SEXUAL THOUGHTS" },
    { value: "OBSESSIVE THOUGHTS OF COMMITTING SUICIDE", label: "OBSESSIVE THOUGHTS OF COMMITTING SUICIDE" },
    { value: "OBSESSIVE THOUGHTS OF DIRT", label: "OBSESSIVE THOUGHTS OF DIRT" },
    { value: "OBSESSIVE THOUGHTS OF HARMING OTHERS", label: "OBSESSIVE THOUGHTS OF HARMING OTHERS" },
    { value: "OBSESSIVE THOUGHTS OF HARMING OWN BABY", label: "OBSESSIVE THOUGHTS OF HARMING OWN BABY" },
    { value: "OBSESSIVE THOUGHTS RELATED TO GOD", label: "OBSESSIVE THOUGHTS RELATED TO GOD" },
    { value: "OVERCONFIDENCE", label: "OVERCONFIDENCE" },
    { value: "PAIN-LOWER BACK", label: "PAIN-LOWER BACK" },
    { value: "PAIN-LOWER LIMB", label: "PAIN-LOWER LIMB" },
    { value: "PAIN-UPPER BACK", label: "PAIN-UPPER BACK" },
    { value: "PAIN-UPPER LIMB", label: "PAIN-UPPER LIMB" },
    { value: "PHOBIC COMPANION", label: "PHOBIC COMPANION" },
    { value: "PR ON HEAD", label: "PR ON HEAD" },
    { value: "PR ON THROAT", label: "PR ON THROAT" },
    { value: "PREMATURE EJACULATION", label: "PREMATURE EJACULATION" },
    { value: "PREOCCUPATION WITH DISEASE", label: "PREOCCUPATION WITH DISEASE" },
    { value: "PREOCCUPATION WITH PHYSICAL SYMPTOMS", label: "PREOCCUPATION WITH PHYSICAL SYMPTOMS" },
    { value: "PRESSURED SPEECH", label: "PRESSURED SPEECH" },
    { value: "PYROMANIA", label: "PYROMANIA" },
    { value: "RESTLESSNESS", label: "RESTLESSNESS" },
    { value: "ROAMING AROUND AIMLESSLY", label: "ROAMING AROUND AIMLESSLY" },
    { value: "ROAMING AROUND SOCIALIZING WITH PEOPLE", label: "ROAMING AROUND SOCIALIZING WITH PEOPLE" },
    { value: "RUMINATION OF THOUGHTS", label: "RUMINATION OF THOUGHTS" },
    { value: "SELF ABSORBED", label: "SELF ABSORBED" },
    { value: "SELF REFERENTIALITY", label: "SELF REFERENTIALITY" },
    { value: "SEMEN  IN URINE", label: "SEMEN  IN URINE" },
    { value: "SINGING  SONGS", label: "SINGING  SONGS" },
    { value: "SMILING TO SELF", label: "SMILING TO SELF" },
    { value: "SOCIAL WITHDRAWAL", label: "SOCIAL WITHDRAWAL" },
    { value: "STARTLED RESPONSES", label: "STARTLED RESPONSES" },
    { value: "SUICIDAL ATTEMPTS", label: "SUICIDAL ATTEMPTS" },
    { value: "SUICIDAL IDEAS", label: "SUICIDAL IDEAS" },
    { value: "TALKATIVENESS", label: "TALKATIVENESS" },
    { value: "TANGENTIALITY", label: "TANGENTIALITY" },
    { value: "TINGLING NUMBNESS IN BACK", label: "TINGLING NUMBNESS IN BACK" },
    { value: "TINGLING NUMBNESS IN HEAD", label: "TINGLING NUMBNESS IN HEAD" },
    { value: "TINGLING NUMBNESS IN LIMBS", label: "TINGLING NUMBNESS IN LIMBS" },
    { value: "TINGLING NUMBNESS IN WHOLE BODY", label: "TINGLING NUMBNESS IN WHOLE BODY" },
    { value: "URGENCY TO MEET DOC", label: "URGENCY TO MEET DOC" },
    { value: "WEEPING SPELLS", label: "WEEPING SPELLS" },
    { value: "WORD SALAD", label: "WORD SALAD" },
    { value: "other", label: "Other" },
]
export default symptomsOptions